---
title: "November 6 Daily R"
author: "Ruth Holloway"
date: "11/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#my code from yesterday
breakfast<-c("leftover cupcake", "clementines", "sheep cheese and toast", "tuna donburi", "avocado toast")
days<-c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
temperature<-c(39, 46, 46, 45, 36)
first.meeting<-c("3:00", "1:00", "8:00", "9:00", "12:00")

this.week<-matrix(c(breakfast, temperature, first.meeting), ncol=3)
rownames(this.week)<-days
colnames(this.week)<-c("breakfast", "temperature", "first meeting")
this.week

dat<-as.data.frame(this.week)
dat$rating<-c(1,1,3,5,4) #variable for hor good my breakfast was on a scale of 1-5
dat

strptime(dat$first.meeting, format = "%Y-%m-%d") #convert to time variable

boxplot(rating~first.meeting, data=dat)
new_order <- with(dat, reorder(first.meeting , rating, median , na.rm=T))
boxplot(dat$rating ~ new_order , xlab="time of first meeitng" , main="")
#so this has it in order of highest rating, which is fine for now, but eventually I'll want it to be in order of the time at which I had my first meeting
```

