---
title: "October 3 Daily R"
author: "Ruth Holloway"
date: "10/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
dat <- read_dta("Data/Democracy Cross-National Data V4.1 09092015.dta")
stopifnot(length(unique(dat$Nation)) == nrow(dat))
stopifnot(all(table(dat$Nation) == 1))
View(dat)

dat$ICRGStand2007 #variable measuring quality of governance
dat$CPI2007 #corruption perception index
dat$CalFHStand2007 #Freedom House liberal democracy rating

fit1<-lm(ICRGStand2007~CPI2007, data=dat) #relationship between corruption perception and quality of governance
summary(fit1)

library(ggplot2)
ggplot(dat) + 
  geom_jitter(aes(CPI2007, ICRGStand2007), colour="blue") + geom_smooth(aes(CPI2007, ICRGStand2007), colour="magenta", method=lm, se=FALSE)


fit2<-lm(ICRGStand2007~CalFHStand2007, data=dat) #relationship between liberal democracy and quality of governance
summary(fit2)
ggplot(dat) + 
  geom_jitter(aes(CalFHStand2007, ICRGStand2007), colour="orange") + geom_smooth(aes(CalFHStand2007, ICRGStand2007), colour="purple", method=lm, se=FALSE)

fit3<-lm(ICRGStand2007~CPI2007+CalFHStand2007+CPI2007*CalFHStand2007, data=dat) #model including all variables of interest
summary(fit3) #something I'd be interested in learning is how to do a ggplot for different explanatory variables/how to standardize scales so that the variables are comparable
```

